import type { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "mozjpeg-q90",
    label: "MozJPEG q90",
    format: "mozjpeg",
    mime: "image/jpeg",
    ext: "jpg",
    preservesAlpha: false,
    options: { format: "mozjpeg", quality: 90 },
  },
  {
    id: "mozjpeg-q80",
    label: "MozJPEG q80",
    format: "mozjpeg",
    mime: "image/jpeg",
    ext: "jpg",
    preservesAlpha: false,
    options: { format: "mozjpeg", quality: 80 },
  },
  {
    id: "mozjpeg-q70",
    label: "MozJPEG q70",
    format: "mozjpeg",
    mime: "image/jpeg",
    ext: "jpg",
    preservesAlpha: false,
    options: { format: "mozjpeg", quality: 70 },
  },
  {
    id: "webp-q90",
    label: "WebP q90",
    format: "webp",
    mime: "image/webp",
    ext: "webp",
    preservesAlpha: true,
    options: { format: "webp", quality: 90 },
  },
  {
    id: "webp-q80",
    label: "WebP q80",
    format: "webp",
    mime: "image/webp",
    ext: "webp",
    preservesAlpha: true,
    options: { format: "webp", quality: 80 },
  },
  {
    id: "webp-q70",
    label: "WebP q70",
    format: "webp",
    mime: "image/webp",
    ext: "webp",
    preservesAlpha: true,
    options: { format: "webp", quality: 70 },
  },
  {
    id: "webp-ll",
    label: "WebP lossless",
    format: "webp-lossless",
    mime: "image/webp",
    ext: "webp",
    preservesAlpha: true,
    options: { format: "webp-lossless", effort: 6 },
  },
  {
    id: "avif-q60",
    label: "AVIF q60",
    format: "avif",
    mime: "image/avif",
    ext: "avif",
    preservesAlpha: true,
    options: { format: "avif", quality: 60, speed: 6 },
  },
  {
    id: "avif-q50",
    label: "AVIF q50",
    format: "avif",
    mime: "image/avif",
    ext: "avif",
    preservesAlpha: true,
    options: { format: "avif", quality: 50, speed: 6 },
  },
  {
    id: "avif-q35",
    label: "AVIF q35",
    format: "avif",
    mime: "image/avif",
    ext: "avif",
    preservesAlpha: true,
    options: { format: "avif", quality: 35, speed: 4 },
  },
  {
    id: "jxl-q88",
    label: "JXL q88",
    format: "jxl",
    mime: "image/jxl",
    ext: "jxl",
    preservesAlpha: true,
    options: { format: "jxl", quality: 88, effort: 7 },
  },
  {
    id: "jxl-q75",
    label: "JXL q75",
    format: "jxl",
    mime: "image/jxl",
    ext: "jxl",
    preservesAlpha: true,
    options: { format: "jxl", quality: 75, effort: 7 },
  },
  {
    id: "png-oxi",
    label: "PNG + OxiPNG",
    format: "png-oxi",
    mime: "image/png",
    ext: "png",
    preservesAlpha: true,
    options: { format: "png-oxi", level: 3 },
  },
];

export const PRESET_BY_ID: Record<string, Preset> = Object.fromEntries(
  PRESETS.map((p) => [p.id, p]),
);
