name: Build Website

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Build website
        run: yarn && yarn build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          find ./ -maxdepth 1 ! -name "dist" ! -name ".git" ! -name "." -exec rm -rf {} \; && \
          mv dist/* . && \
          rm -rf dist && \
          git config --global user.name "github-actions[bot]" && \
          git config --global user.email "github-actions@github.com" && \
          git add . && \
          git commit -m "Deploy to GitHub Pages" && \
          git push --force git+https://${GITHUB_TOKEN}@github.com/${REPOSITORY}.git HEAD:gh-pages